// Generated by gen_fonts.pl
// config file: fonts.cfg

#if defined(__AVR__)
	#include <avr/pgmspace.h>
	#define fontdatatype const uint8_t
#elif defined(__PIC32MX__)
	#define PROGMEM
	#define fontdatatype const unsigned char
#elif defined(__arm__)
	#define PROGMEM
	#define fontdatatype const unsigned char
#endif

#ifdef __cplusplus
extern "C" {
#endif

extern fontdatatype SmallFont [] PROGMEM;
extern fontdatatype BigNumbers [] PROGMEM;
#ifdef __cplusplus
}
#endif
